// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8foYp-gIhym_VLoHTCSadBj6z_76jAF8',
    appId: '1:805022307543:web:7d930c1b95f92e28da4c92',
    messagingSenderId: '805022307543',
    projectId: 'family-tree-app-b64e0',
    authDomain: 'family-tree-app-b64e0.firebaseapp.com',
    storageBucket: 'family-tree-app-b64e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLiKkIPoqsQBLUkC4Dpn0eF1Otyt-6rAE',
    appId: '1:805022307543:android:08d54de00f77ef56da4c92',
    messagingSenderId: '805022307543',
    projectId: 'family-tree-app-b64e0',
    storageBucket: 'family-tree-app-b64e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBMweKY0r22R9_vv1yO-jDjir1spzMRg',
    appId: '1:805022307543:ios:baf5476b3bd06c82da4c92',
    messagingSenderId: '805022307543',
    projectId: 'family-tree-app-b64e0',
    storageBucket: 'family-tree-app-b64e0.firebasestorage.app',
    iosBundleId: 'com.example.familytree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZBMweKY0r22R9_vv1yO-jDjir1spzMRg',
    appId: '1:805022307543:ios:baf5476b3bd06c82da4c92',
    messagingSenderId: '805022307543',
    projectId: 'family-tree-app-b64e0',
    storageBucket: 'family-tree-app-b64e0.firebasestorage.app',
    iosBundleId: 'com.example.familytree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8foYp-gIhym_VLoHTCSadBj6z_76jAF8',
    appId: '1:805022307543:web:dd9e36e48789ec60da4c92',
    messagingSenderId: '805022307543',
    projectId: 'family-tree-app-b64e0',
    authDomain: 'family-tree-app-b64e0.firebaseapp.com',
    storageBucket: 'family-tree-app-b64e0.firebasestorage.app',
  );
}
